//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpiderService.Db.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        public ContentType()
        {
            this.Links = new HashSet<Link>();
        }
    
        public int Id { get; set; }
        public string LinkContentType { get; set; }
        public string FileExtension { get; set; }
    
        public virtual ICollection<Link> Links { get; set; }
    }
}
