// <auto-generated />
namespace WebSpiderService.Db.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class LinkContentTypeRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkContentTypeRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201401121355065_LinkContentTypeRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
